DROP TABLE USER IF EXISTS CASCADE;
DROP TABLE USERS IF EXISTS CASCADE;

CREATE TABLE USERS 
(	
	ID VARCHAR(50) primary key,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	LEVEL INTEGER NOT NULL, 
	LOGIN INTEGER NOT NULL,
	RECOMMEND INTEGER NOT NULL
);


