DROP TABLE USER IF EXISTS CASCADE;
DROP TABLE USERS IF EXISTS CASCADE;

CREATE TABLE USERS 
(	
	ID VARCHAR(50) primary key,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100),
	LEVEL INTEGER, 
	LOGIN INTEGER,
	RECOMMEND INTEGER
);


